services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    command: >
      mlflow server
      --backend-store-uri file:///work/mlruns
      --artifacts-destination /work/mlruns
      --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/work/mlruns
    ports: ["5000:5000"]

  bootstrap:
    build: .
    command: python -m recsys.bootstrap_once
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=MovieLensXGB
      - ALIAS_NAME=prod
    depends_on:
      mlflow:
        condition: service_started
    restart: "no"

  api:
    build: .
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data/processed:/app/data/processed
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    ports: ["8000:8000"]
